### PR TITLE
setting up the package + adding first fun

### PR DESCRIPTION
**Pull request by papsti**
getting two notes when running `devtools::check()`

```
── R CMD check results ────── macpan2helpers 0.0.0.9000 ────
Duration: 41.4s

❯ checking top-level files ... NOTE
  File
    LICENSE
  is not mentioned in the DESCRIPTION file.

❯ checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: 'macpan2'
    All declared Imports should be used.
```

not sure why the first one is triggering as i used `usethis::use_gpl3_license()` to set up the `LICENSE` file.

for the second one, we obviously want users of `macpan2helpers` to have `macpan2` installed, but it's not exactly an `Import`. not sure what the proper paradigm is here...?

### CODE REVIEW

**Comment by papsti** [comment]
once this is merged, will it be enough to add `macpan2helpers` to the `Suggests` field of the `macpan2` `DESCRIPTION` file? i'm asking since `macpan2helpers` is exclusively on GitHub and not CRAN. i imagine it's fine as suggested packages are up to the user to install. we could add `macpan2helpers` installation instructions to the `macpan2` README?

**Review by stevencarlislewalker — COMMENTED** [review]
Thank you!  That is my review.

**Comment by papsti** [comment]
as a follow up, i went do
```
remotes::install_github("canmod/macpan2helpers@ip-setup")
```
in my RStudio session where i'm working on `macpan2`, and i got the following warning
```
Skipping 1 packages not available: macpan2
```
so I guess if we want the `macpan2` to auto-install with `macpan2helpers`, we'd need to a bit more work. but i think we can just leave it like this.

**Comment by stevencarlislewalker** [comment]
> once this is merged, will it be enough to add macpan2helpers to the Suggests field of the macpan2 DESCRIPTION file? i'm asking since macpan2helpers is exclusively on GitHub and not CRAN. i imagine it's fine as suggested packages are up to the user to install. we could add macpan2helpers installation instructions to the macpan2 README?

We have a [drat](https://github.com/eddelbuettel/drat) repo to use instead of cran.  This will allow use to manage dependencies in a cran-like way.  I don't mind taking care of this.

Thanks for all of this!

**Comment by stevencarlislewalker** [comment]
Also, I'm going to just give you maintainer permission to reduce the changes that you are blocked by doing anything.

**Comment by papsti** [comment]
OK great. i will still avoid making changes directly to `main` to save me from myself.

**Pull request merged**
